In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a.dtype

dtype('int64')

In [5]:
a[1,2]

7

In [6]:
a[1,2] = -7

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, -7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# range (i, m ) i.........m-1
for i in range(5,10):
  print(i, end=" ")

5 6 7 8 9 

In [12]:
# x:m => x.x+1.x+2.......m-1

#a[0:2, 1:3]
a[:2, 1:3]

array([[ 2,  3],
       [ 6, -7]])

In [13]:
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6, -7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 6, -7,  8],
       [10, 11, 12]])

In [21]:
data = [[3.1,2.2,5.1,1],
        [4.2,5.1,3.4,0],
        [3.1,0.2,5.1,1],
        [8.2,7.2,-11,1]]
data = np.array(data)
x = data[:,:3]
y = data[:,-1]

In [22]:
x

array([[  3.1,   2.2,   5.1],
       [  4.2,   5.1,   3.4],
       [  3.1,   0.2,   5.1],
       [  8.2,   7.2, -11. ]])

In [23]:
y

array([1., 0., 1., 1.])

In [24]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [30]:
from math import sqrt
bool_a = (a==int(sqrt(36)))

In [31]:
bool_a

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [32]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [33]:
r = np.random.random(20)

In [34]:
r

array([0.58851155, 0.69321844, 0.00774032, 0.73972126, 0.86848846,
       0.0955282 , 0.86825048, 0.41249725, 0.87468234, 0.44819095,
       0.22298311, 0.01041992, 0.69315449, 0.27075897, 0.89745757,
       0.28066984, 0.6403662 , 0.20115871, 0.9176441 , 0.79830426])

In [39]:
r.reshape((5,4))

array([[0.58851155, 0.69321844, 0.00774032, 0.73972126],
       [0.86848846, 0.0955282 , 0.86825048, 0.41249725],
       [0.87468234, 0.44819095, 0.22298311, 0.01041992],
       [0.69315449, 0.27075897, 0.89745757, 0.28066984],
       [0.6403662 , 0.20115871, 0.9176441 , 0.79830426]])

In [41]:
rr = r[r > 0.6]

In [43]:
rr

array([0.69321844, 0.73972126, 0.86848846, 0.86825048, 0.87468234,
       0.69315449, 0.89745757, 0.6403662 , 0.9176441 , 0.79830426])

In [45]:
rr.shape

(10,)

In [49]:
rr.reshape(2,5)

array([[0.69321844, 0.73972126, 0.86848846, 0.86825048, 0.87468234],
       [0.69315449, 0.89745757, 0.6403662 , 0.9176441 , 0.79830426]])

In [50]:
x = np.array([1,2,-3,5,8,9,4,-200,124,0])

In [51]:
x

array([   1,    2,   -3,    5,    8,    9,    4, -200,  124,    0])

In [52]:
x.sort()

In [53]:
x

array([-200,   -3,    0,    1,    2,    4,    5,    8,    9,  124])

In [58]:
x = np.array([2,-3,4,-200,124,0])
for i in range(x.size-1):
  if x[i]>x[i+1]:
    x[i],x[i+1]=x[i+1],x[i]

In [59]:
x

array([  -3,    2, -200,    4,    0,  124])

In [60]:
for i in range(x.size-1):
  if x[i]>x[i+1]:
    x[i],x[i+1]=x[i+1],x[i]
x

array([  -3, -200,    2,    0,    4,  124])

In [61]:
for i in range(x.size-1):
  if x[i]>x[i+1]:
    x[i],x[i+1]=x[i+1],x[i]
x

array([-200,   -3,    0,    2,    4,  124])

In [56]:
x.size

6

In [57]:
len([1,2,3,4,5,6])

6

In [63]:
x = np.array([1,2,-3,5,8,9,4,-200,124,0])
for j in range(x.size-1):
  for i in range(x.size-1):
    if x[i]>x[i+1]:
      #x[i],x[i+1]=x[i+1],x[i]
      t = x[i]
      x[i] = x[i+1]
      x[i+1]= t
x

array([-200,   -3,    0,    1,    2,    4,    5,    8,    9,  124])

In [65]:
def array_sort(array):
  for j in range(array.size-1):
    for i in range(array.size-1):
      if array[i]>array[i+1]:
        #array[i],array[i+1]=array[i+1],array[i]
        t = array[i]
        array[i] = array[i+1]
        array[i+1]= t
  return array

In [66]:
x = np.array([11,22,-30,5,80,90,4,-2000,124,0])

In [68]:
z = array_sort(x)

In [69]:
z

array([-2000,   -30,     0,     4,     5,    11,    22,    80,    90,
         124])

In [70]:
z.dtype

dtype('int64')

In [82]:
y = np.array([11,22,-30,5,80,90,4,-2000,124,0])
m,n = 1 ,2

y

array([   11,    22,   -30,     5,    80,    90,     4, -2000,   124,
           0])

In [72]:
from math import pow
def fff(a,b):
  a = pow(a,b)
  b = a+b
  return b

In [78]:
print(fff(m,n))

print(m,n)

3.0
1 2


In [83]:
y_sorted = array_sort(y)

In [84]:
y

array([-2000,   -30,     0,     4,     5,    11,    22,    80,    90,
         124])

In [85]:
y_sorted

array([-2000,   -30,     0,     4,     5,    11,    22,    80,    90,
         124])

In [86]:
from sklearn import datasets
iris = datasets.load_iris()

In [91]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [90]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])