In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(6,)


In [7]:
list1 = [5,6,-1,3]

In [8]:
list1[2]

-1

In [9]:
a[2]

3

In [10]:
list1[3]=25

In [11]:
list1

[5, 6, -1, 25]

In [12]:
a[2] = -3

In [13]:
a

array([ 1,  2, -3,  4,  5,  6])

In [22]:
b = np.array([[1,2,3,-1,5],
              [4,5,6,-2,5],
              [7,8,9,-3,5],
              [0,3,5,-4,5]])
b.shape

(4, 5)

In [23]:
l2 = [[1,2,3,-1,5],
      [4,5,6,-2,5],
              [7,8,9,-3,5],
              [0,3,5,-4,5]]

In [24]:
l2

[[1, 2, 3, -1, 5], [4, 5, 6, -2, 5], [7, 8, 9, -3, 5], [0, 3, 5, -4, 5]]

In [25]:
l2[1][4] = -100

In [26]:
l2

[[1, 2, 3, -1, 5], [4, 5, 6, -2, -100], [7, 8, 9, -3, 5], [0, 3, 5, -4, 5]]

In [27]:
b[1, 4]

5

In [31]:
b[1, 4] = -3.14

In [32]:
b

array([[ 1,  2,  3, -1,  5],
       [ 4,  5,  6, -2, -3],
       [ 7,  8,  9, -3,  5],
       [ 0,  3,  5, -4,  5]])

In [37]:
c = np.array([3.14,2,1])

In [38]:
c

array([3.14, 2.  , 1.  ])

In [39]:
a = -3.14

In [40]:
type(a)

float

In [41]:
a = int(-3.14)
# a = int(a)

In [42]:
type(a)

int

In [43]:
a

-3

In [54]:
a = np.zeros((3,5),dtype=int) #default = float 
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [52]:
a[2,4] = 12.5

In [53]:
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12]])

In [55]:
b = np.ones((10,2))

In [56]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
b[8,1] = -1

In [58]:
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1., -1.],
       [ 1.,  1.]])

In [63]:
c = np.full((3,4), 25, dtype = float)

In [64]:
c

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

In [66]:
x = 5
sh = (5,7)
y = np.full(sh, x)

In [67]:
y

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [68]:
type(sh)

tuple

In [69]:
e = np.eye(5) #I

In [70]:
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
m = (3,4)
r = np.random.random(m)

In [75]:
r

array([[0.69916683, 0.12259419, 0.59495357, 0.09874622],
       [0.93308876, 0.22821517, 0.16891167, 0.75518583],
       [0.94710261, 0.11184081, 0.73994736, 0.8515063 ]])

In [84]:
r2 = np.random.randint(low = 8, high = 12, size=5)

In [87]:
r2

array([10,  8, 11,  9, 10])

In [86]:
type(r2)

numpy.ndarray

In [88]:
r2.shape

(5,)

In [89]:
type(r)

numpy.ndarray

In [90]:
print(r.dtype)

float64


In [91]:
print(r2.dtype)

int64


In [115]:
#add
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)


In [94]:
x

array([[1., 2.],
       [3., 4.]])

In [102]:
y

array([[5., 6.],
       [7., 8.]])

In [97]:
x.dtype

dtype('float64')

In [99]:
y.dtype

dtype('float32')

In [101]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [116]:
c = np.add(x,y)


In [104]:
c

array([[ 6.,  8.],
       [10., 12.]])

In [117]:
c.dtype

dtype('float64')

In [118]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [119]:
s = np.subtract(x,y)

In [120]:
s

array([[-4., -4.],
       [-4., -4.]])

In [121]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [122]:
m = np.multiply(x,y)

In [123]:
m

array([[ 5., 12.],
       [21., 32.]])

In [124]:
m.dtype

dtype('float64')

In [125]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [126]:
d = np.divide(x,y)
d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [128]:
sq = np.sqrt(x)
sq

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [129]:
rsqrt = np.sqrt(r2)
rsqrt

array([3.16227766, 2.82842712, 3.31662479, 3.        , 3.16227766])

In [134]:
a = np.array([1, 3, -5] )
b = np.array([4, -2, -1])

np.dot(a,b)

3

In [135]:
a.dot(b)

3

In [136]:
x

array([[1., 2.],
       [3., 4.]])

In [137]:
y 

array([[5., 6.],
       [7., 8.]])

In [138]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [139]:
x 

array([[1., 2.],
       [3., 4.]])

In [140]:
np.sum(x)

10.0

In [141]:
bb = a*b

In [142]:
bb

array([ 4, -6,  5])

In [143]:
np.sum(bb)

3

In [144]:
a.dot(b)

3

In [145]:
x

array([[1., 2.],
       [3., 4.]])

In [148]:
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))


[4. 6.]
[3. 7.]


In [149]:
x


array([[1., 2.],
       [3., 4.]])